### ISSUE TITLE
Ambigous role of goal_generator.py

### ISSUE THREAD

**Issue by anubhav4sachan** [truthless11/MADPL#1]
`goal_generator.py` has a class named `GoalGenerator` with various functions in it, which makes the class quite useful, like generation of goal distribution, getting domain goal, getting user goal etc. 

The file is hard-coded for annotated MultiWoz Dataset, and hence it is creating difficulties for the contributors to understand the objective of the file.

Can you share a doc or maybe add a section in README.md file to highlight the importance of the file and how it is useful for the MADPL Algorithm.

**Comment by truthless11** [comment]
@anubhav4sachan There is not a doc of `goal_generator.py` now, but you can refer to my [latest paper](https://arxiv.org/abs/2005.07362) for more details. Though there is a slight difference between the goal generator described in this paper and the one used in MADPL, I hope this would help you.
