### ISSUE TITLE
Could you please share the checkpoint of the pretrained baseline model?

### ISSUE THREAD

**Issue by James-Yip** [truthless11/MADPL#2]
I wanna run some experiments based on the pretrained  SL baseline model, could you please share the checkpoint of the pretrained model (where success_rate=49.7%, as mentioned in the paper)?
Thank you!
PS: I run the command in README to pretrain (`python main.py --pretrain True --save_dir model_pre`), but got a model with 46% success rate, which is slightly lower than the pretrained model mentioned in the paper.

**Comment by truthless11** [comment]
@James-Yip Sure. Here are the parameters for [pretrained model](https://drive.google.com/file/d/1xaBExuxPteKFydLj9Xw777etV-inH7HN/view?usp=sharing)
