### ISSUE TITLE
MADPL、ConvLab-2

### ISSUE THREAD

**Issue by gumowangfei** [truthless11/MADPL#4]
How can MADPL integrate with ConvLab-2.

**Comment by gumowangfei** [comment]
请问，人工评估部分是如何做的？此源码中无相关代码，论文中没有看的特别明白，可否详细介绍下？非常谢谢！

**Comment by truthless11** [comment]
You have to implement a `PipelineAgent` as the system policy, and create your own `Environment` as the user policy to integrate MADPL into ConvLab-2. Try to rewrite the `MultiWozEvaluator` class to change the reward function.

As for human evaluation, we transform the dialog acts that MADPL or other baselines generates into the natural language via templates, then show them to the Turkers. Pair-wise evaluation is conducted that Turker selects the better dialog according to each metric.
